### ISSUE TITLE
Destroy method does not always resolve / reject

### ISSUE THREAD

**Issue by danimoh** [nimiq-network/jungle-db#1]
The destroy method in browser/JungleDB.js does sometimes not resolve but neither reject.

Speculating:
It might be that after `(await backend).close()`, `this._indexedDB.deleteDatabase(this._databaseDir)` fails but for some reason the onerror does not seem to get triggered.

As indexedDB (apparently) does not provide a callback to notify when a database was closed by the user a timeout might help.

**Comment by paberr** [comment]
I could not verify this so far.
If it occurs again, I'll reopen the issue.
